from . import s_hr_employee
from . import s_res_config_settings
from . import s_project_project
from . import s_compensation_benefit
from . import s_contact_number
from . import s_valid_ids
from . import s_family_members
from . import s_license
from . import s_education
from . import s_external_work_history
from . import s_internal_work_history
from . import s_training_development
from . import s_res_users